{{- if .Values.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace.values.namespace.name }}
  namespace: "argocd-system"
  annotations:
    argocd.argoproj.io/sync-wave: "600"
spec:
  destination:
    namespace: {{ .Values.namespace.values.namespace.name  }}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: "certmanager"
      {{- with .Values.certmanager.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: {{ .Values.certmanager.source.url }}
    targetRevision: {{ .Values.certmanager.source.targetRevision }}
    chart: cert-manager
    # path: ./charts/ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
{{- end -}}