apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd-system
spec:
  generators:
    - git:
        repoURL: https://github.com/nicolastakashi/homelab.git
        revision: main
        directories:
          - path: argo/apps/*
  template:
    metadata:
      name: "{{path.basename}}-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/nicolastakashi/homelab.git
        targetRevision: main
        path: "{{path}}"
        helm:
          releaseName: "{{path.basename}}"
          values: |
            namespace:
              name: {{path.basename}}
            source:
              url: https://github.com/nicolastakashi/homelab.git
              targetRevision: main
              path: argo/apps/{{path}}
          valueFiles:
            - values.yaml
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 15s
            factor: 1
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
