apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/nicolastakashi/homelab.git
        revision: HEAD
        directories:
          - path: argo/apps/*
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: default
      source:
        repoURL: https://github.com/nicolastakashi/homelab.git
        targetRevision: HEAD
        path: "{{path}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 15s
            factor: 1
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
