opentelemetry-collector:
  mode: "deployment"
  clusterRole:
    create: true
    rules:
      - apiGroups: [""]
        resources:
          - nodes
          - nodes/proxy
          - nodes/metrics
          - services
          - endpoints
          - pods
        verbs: ["get", "list", "watch"]
      - apiGroups:
          - extensions
        resources:
          - ingresses
        verbs: ["get", "list", "watch"]
      - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/probes"]
        verbs: ["get"]

  image:
    # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
    repository: "otel/opentelemetry-collector-contrib"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.128.0"
    # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
    digest: ""

  extraEnvs:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

  config:
    exporters:
      prometheusremotewrite:
        endpoint: "http://thanos-receive.observability.svc.cluster.local:19291/api/v1/receive"
        external_labels:
          k8s_cluster_name: "pt-north-1"
        send_metadata: true
        tls:
          insecure: true

    receivers:
      jaeger: null
      zipkin: null
      prometheus:
        target_allocator:
          endpoint: http://opentelemetry-target-allocator.observability.svc.cluster.local:80
          interval: 30s
          collector_id: ${env:MY_POD_NAME}
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 15s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    service:
      telemetry:
        logs:
          level: warn
      pipelines:
        logs: null
        metrics:
          exporters:
            - prometheusremotewrite
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces: null
