apiVersion: v2
appVersion: v2.2.2
name: certmanager
description: A Helm chart for certmanager, a declarative, GitOps continuous delivery tool for Kubernetes.
type: application
version: 0.1.0
dependencies:
  - name: cert-manager
    version: v1.15.2
    repository: https://charts.jetstack.io
