{{- if .Values.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace.values.namespace.name }}
  namespace: "argocd-system"
  annotations:
    argocd.argoproj.io/sync-wave: "600"
spec:
  destination:
    namespace: {{ .Values.namespace.values.namespace.name  }}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: "cilium"
      {{- with .Values.cilium.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: {{ .Values.cilium.source.url }}
    targetRevision: {{ .Values.cilium.source.targetRevision }}
    path: ./install/kubernetes/cilium
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
{{- end -}}