kube-state-metrics:
  revisionHistoryLimit: 0
  namespaceOverride: "observability"
  fullnameOverride: "kube-state-metrics"
  prometheus:
    monitor:
      enabled: true
      http:
        honorLabels: true
      metrics:
        honorLabels: true
