apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector-metrics-cluster-role
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - pod
    verbs:
      - "get"
      - "watch"
      - "list"
