apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace.values.namespace.name }}
  namespace: "argocd-system"
  annotations:
    argocd.argoproj.io/sync-wave: "600"
spec:
  destination:
    namespace: {{ .Values.namespace.values.namespace.name  }}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: "cloudflare-tunnel"
      {{- with .Values.tunnel }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: https://github.com/nicolastakashi/homelab.git
    targetRevision: HEAD
    path: ./charts/cloudflare-tunnel
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
