apiVersion: v2
name: node-exporter
description: A Helm chart for node-exporter, a declarative, GitOps continuous delivery tool for Kubernetes.
type: application
version: 0.1.0
dependencies:
  - name: prometheus-node-exporter
    version: 4.37.2
    repository: https://prometheus-community.github.io/helm-charts
