cilium:
  rollOutCiliumPods: true
  k8sServiceHost: 192.168.1.117
  k8sServicePort: 6443

  MTU: 1500

  kubeProxyReplacement: "true"
  # bpf:
  #   masquerade: true
  #   hostLegacyRouting: true
  operator:
    replicas: 1
    rollOutPods: true

  l2announcements:
    enabled: true

  externalIPs:
    enabled: true

  k8sClientRateLimit:
    qps: 50
    burst: 200

  ingressController:
    enabled: true
    default: true
    loadbalancerMode: shared
    service:
      annotations:
        io.cilium/lb-ipam-ips: 192.168.1.140
