cilium:
  rollOutCiliumPods: true
  k8sServiceHost: 192.168.1.117
  k8sServicePort: 6443

  MTU: 1500

  kubeProxyReplacement: "true"

  operator:
    replicas: 1
    rollOutPods: true

  l2announcements:
  enabled: true

  externalIPs:
    enabled: true

  k8sClientRateLimit:
    qps: 50
    burst: 200
