cilium:
  MTU: 1500
  kubeProxyReplacement: true
  ingressController:
    enabled: true
    loadbalancerMode: dedicated
  operator:
    replicas: 1
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
