namespace:
  values:
    namespace:
      name: cloudflare-tunnel

tunnel:
  # Cloudflare parameters.
  cloudflare:
    ingress:
      - hostname: grafana.ntakashi.com
        service: http://cilium-ingress.cilium.svc.cluster.local:80
      - hostname: argocd.ntakashi.com
        service: http://cilium-ingress.cilium.svc.cluster.local:80
