apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector-metrics
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-collector-metrics
subjects:
- kind: ServiceAccount
  name: opentelemetry-collector-metrics-collector-targetallocator
  namespace: {{ .Release.Namespace }}