thanos:
  objstoreConfig: |
    type: FILESYSTEM
    config:
      directory: "/srv/thanos"

  query:
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn

  queryFrontend:
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn

  receive:
    enabled: true
    tsdbRetention: 4h
