thanos:
  objstoreConfig: |
    type: FILESYSTEM
    config:
      directory: "/srv/thanos"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  query:
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn

  queryFrontend:
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn

  receive:
    enabled: true
    logFormat: json
    logLevel: warn
    tsdbRetention: 4h

  receiveDistributor:
    enabled: false
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn
