apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector-agent
  namespace: {{ .Release.Namespace }}
spec:
  mode: daemonset
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  config: |
    receivers:
      hostmetrics:
        collection_interval: 30s
        scrapers:
          load:
          network:
          disk:
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          memory:
            metrics:
              system.memory.limit:
                enabled: true
              system.memory.utilization:
                enabled: true
          filesystem:
            exclude_mount_points:
              mount_points:
                - /dev/*
                - /proc/*
                - /sys/*
                - /run/k3s/containerd/*
                - /run/containerd/runc/*
                - /var/lib/docker/*
                - /var/lib/kubelet/*
                - /snap/*
              match_type: regexp
            exclude_fs_types:
              fs_types:
                - autofs
                - binfmt_misc
                - bpf
                - cgroup2
                - configfs
                - debugfs
                - devpts
                - devtmpfs
                - fusectl
                - hugetlbfs
                - iso9660
                - mqueue
                - nsfs
                - overlay
                - proc
                - procfs
                - pstore
                - rpc_pipefs
                - securityfs
                - selinuxfs
                - squashfs
                - sysfs
                - tracefs
              match_type: strict


    extensions:
      health_check:
      zpages:
        endpoint: localhost:55679
      pprof:
        endpoint: localhost:1777

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 20
      resourcedetection/k8s:
        detectors: [k8snode]
        timeout: 2s
        override: false
      transform:
        metric_statements:
          - context: datapoint
            statements:
            - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
            - set(attributes["container"], resource.attributes["k8s.container.name"])
            - set(attributes["pod"], resource.attributes["k8s.pod.name"])
        

    exporters:
      debug:
      prometheusremotewrite:
        endpoint: "http://thanos-receive.thanos.svc.cluster.local:19291/api/v1/receive"
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: "warn"
        metrics:
          address: ${MY_POD_IP}:8888
      extensions: 
        - zpages
        - pprof
        - health_check
      pipelines:
        metrics:
          receivers: 
            - hostmetrics
          processors: 
            - memory_limiter
            - resourcedetection/k8s
            - transform
            - batch
          exporters:
            - prometheusremotewrite