apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-collector-agent
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-collector-agent
subjects:
- kind: ServiceAccount
  name: opentelemetry-collector-agent
  namespace: {{ .Release.Namespace }}