apiVersion: v2
name: cluster
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: argo-cd
    version: 9.4.3
    repository: https://argoproj.github.io/argo-helm
